export interface PECDepartmentSeed {
  id: string;
  name: string;
  code: string;
  description: string;
}

export interface PECClubSeed {
  id: string;
  name: string;
  slug: string;
  category: 'Industry 4.0' | 'Co-Curricular Activities' | 'Extra-Curricular Activities';
  department: string;
  department_id: string;
  faculty_coordinator: string;
  description: string;
  domains: string;
  objectives: string;
  logo_url?: string;
  banner_url?: string;
}

export const PEC_DEPARTMENTS: PECDepartmentSeed[] = [
  {
    id: 'dept-ce',
    name: 'Civil Engineering',
    code: 'CE',
    description: 'Department of Civil Engineering, Sustainable Infrastructure, and Environmental Systems',
  },
  {
    id: 'dept-it',
    name: 'Information Technology',
    code: 'IT',
    description: 'Department of Information Technology, Cloud Computing, and Software Engineering',
  },
  {
    id: 'dept-me',
    name: 'Mechanical Engineering',
    code: 'ME',
    description: 'Department of Mechanical Engineering, Robotics, Thermal Systems, and Additive Manufacturing',
  },
  {
    id: 'dept-cse',
    name: 'Computer Science & Engineering',
    code: 'CSE',
    description: 'Department of Computer Science & Engineering, Distributed Systems, and Computing Platforms',
  },
  {
    id: 'dept-csecs',
    name: 'CSE (Cyber Security)',
    code: 'CSE(CS)',
    description: 'Department of Computer Science & Engineering (Cyber Security and Information Defense)',
  },
  {
    id: 'dept-cseaiml',
    name: 'CSE (AI & ML)',
    code: 'CSE(AIML)',
    description: 'Department of Computer Science & Engineering (Artificial Intelligence and Machine Learning)',
  },
  {
    id: 'dept-cseds',
    name: 'CSE (Data Science)',
    code: 'CSE(DS)',
    description: 'Department of Computer Science & Engineering (Data Science and Big Data Analytics)',
  },
  {
    id: 'dept-cseai',
    name: 'CSE (Artificial Intelligence)',
    code: 'CSE(AI)',
    description: 'Department of Computer Science & Engineering (Artificial Intelligence and Cognition)',
  },
  {
    id: 'dept-ece',
    name: 'Electronics & Communication Engineering',
    code: 'ECE',
    description: 'Department of Electronics & Communication Engineering, VLSI, IoT, and Telecommunications',
  },
  {
    id: 'dept-eee',
    name: 'Electrical & Electronics Engineering',
    code: 'EEE',
    description: 'Department of Electrical & Electronics Engineering, EV Technology, and Power Systems',
  },
  {
    id: 'dept-bsh',
    name: 'Basic Sciences & Humanities',
    code: 'BSH',
    description: 'Department of Basic Sciences and Humanities, Mathematics, English, and Environmental Studies',
  },
];

export const PEC_CLUBS: PECClubSeed[] = [
  // ==========================================
  // Category 1: Industry 4.0 (11 Clubs)
  // ==========================================
  {
    id: 'green-building-club',
    name: 'Green Building Club',
    slug: 'green-building-club',
    category: 'Industry 4.0',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Mr L Praveen Kumar',
    description: 'A student club focused on sustainable construction, energy-efficient buildings, environmentally responsible design, green materials, and innovative approaches to creating healthier and more sustainable built environments.',
    domains: 'Sustainable Construction, Green Building, Energy Efficiency, Eco Materials',
    objectives: 'Promote LEED and IGBC green building standards, sustainable architectural workflows, and energy simulation tools among civil engineering scholars.',
    logo_url: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'gaming-club',
    name: 'Gaming Club',
    slug: 'gaming-club',
    category: 'Industry 4.0',
    department: 'IT',
    department_id: 'dept-it',
    faculty_coordinator: 'Mr D. Konda Babu',
    description: 'A student community focused on gaming, game development, competitive gaming, game technology, interactive experiences, and collaborative activities that encourage creativity, technical skills, and strategic thinking.',
    domains: 'Game Development, Esports, Game Engines, Interactive Media',
    objectives: 'Fosters real-time rendering skills, game loop physics architecture, Unreal/Unity engines, and tactical collegiate esports competitions.',
    logo_url: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'robotics-club',
    name: 'Robotics Club',
    slug: 'robotics-club',
    category: 'Industry 4.0',
    department: 'ME',
    department_id: 'dept-me',
    faculty_coordinator: 'Mr. V. V.N.Sarath',
    description: 'A technical club focused on robotics, automation, mechanical systems, embedded technologies, robotic design, prototyping, and hands-on engineering projects.',
    domains: 'Robotics, Automation, Embedded Systems, Mechatronics',
    objectives: 'Design autonomous wheeled platforms, robotic manipulators, ROS2 kinematic pipelines, and industrial automation prototypes.',
    logo_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'ar-vr-club',
    name: 'AR/VR Club',
    slug: 'ar-vr-club',
    category: 'Industry 4.0',
    department: 'CSE',
    department_id: 'dept-cse',
    faculty_coordinator: 'Mr.A.Avinash',
    description: 'A technology-focused club exploring augmented reality, virtual reality, immersive interfaces, 3D experiences, spatial computing, and practical applications of immersive technologies.',
    domains: 'Augmented Reality, Virtual Reality, Unity 3D, Spatial Computing',
    objectives: 'Build immersive WebXR scenes, headset spatial applications, marker-based AR tracking, and virtual simulation environments.',
    logo_url: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'additive-manufacturing-club',
    name: 'Additive Manufacturing Club',
    slug: 'additive-manufacturing-club',
    category: 'Industry 4.0',
    department: 'ME',
    department_id: 'dept-me',
    faculty_coordinator: 'Mr P. Ram Prasad',
    description: 'A technical club focused on additive manufacturing and 3D printing technologies, covering digital design, prototyping, manufacturing processes, materials, and innovative engineering applications.',
    domains: '3D Printing, Rapid Prototyping, CAD/CAM, Digital Fabrication',
    objectives: 'Provide hands-on FDM and SLA 3D printing training, slicer optimization, generative design CAD, and functional mechanical prototyping.',
    logo_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'cyber-security-club',
    name: 'Cyber Security Club',
    slug: 'cyber-security-club',
    category: 'Industry 4.0',
    department: 'CSE(CS)',
    department_id: 'dept-csecs',
    faculty_coordinator: 'Mrs. K Sireesha',
    description: 'A cybersecurity-focused community exploring information security, ethical security practices, network security, application security, digital forensics, privacy, and practical security awareness.',
    domains: 'Ethical Hacking, Network Security, Cryptography, Threat Defense',
    objectives: 'Organize collegiate capture-the-flag competitions, digital forensic workshops, secure code audits, and cyber hygiene drives.',
    logo_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'cloud-computing-club',
    name: 'Cloud Computing Club',
    slug: 'cloud-computing-club',
    category: 'Industry 4.0',
    department: 'IT',
    department_id: 'dept-it',
    faculty_coordinator: 'Mr K Siva Shankar',
    description: 'A technical club focused on cloud computing concepts, cloud platforms, distributed systems, deployment technologies, scalable applications, and practical cloud-based projects.',
    domains: 'Cloud Architecture, AWS/GCP/Azure, DevOps, Microservices',
    objectives: 'Master containerized deployments, Kubernetes orchestration, serverless microservices, and multi-cloud architectural patterns.',
    logo_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'aiml-turing-club',
    name: 'AI&ML Turing Club',
    slug: 'aiml-turing-club',
    category: 'Industry 4.0',
    department: 'CSE(AIML)',
    department_id: 'dept-cseaiml',
    faculty_coordinator: 'Mrs L.Yamuna',
    description: 'A technical community focused on artificial intelligence and machine learning, including data-driven problem solving, model development, experimentation, responsible AI, and practical applications of intelligent systems.',
    domains: 'Machine Learning, Deep Learning, Computer Vision, Natural Language Processing',
    objectives: 'Develop deep learning pipelines, transformer model fine-tuning, computer vision classification, and applied generative AI solutions.',
    logo_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'iot-club',
    name: 'IoT Club',
    slug: 'iot-club',
    category: 'Industry 4.0',
    department: 'ECE',
    department_id: 'dept-ece',
    faculty_coordinator: 'Dr.Subodh Kumar Panda',
    description: 'A technology club exploring connected devices, sensors, embedded systems, communication technologies, automation, and Internet of Things applications through practical projects and experimentation.',
    domains: 'Internet of Things, Embedded C, Sensor Networks, Edge Computing',
    objectives: 'Engineer ESP32 and ARM Cortex sensor nodes, MQTT telemetry pipelines, industrial sensor interfacing, and edge computing gateways.',
    logo_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'electric-vehicle-club',
    name: 'Electric Vehicle Club',
    slug: 'electric-vehicle-club',
    category: 'Industry 4.0',
    department: 'EEE',
    department_id: 'dept-eee',
    faculty_coordinator: 'Mr. P.V.V.Ramana',
    description: 'A technical club focused on electric mobility, electric vehicle systems, battery technologies, motor drives, charging systems, vehicle electronics, and sustainable transportation technologies.',
    domains: 'EV Powertrains, Battery Management, Power Electronics, Sustainable Mobility',
    objectives: 'Analyze regenerative braking dynamics, lithium-ion battery management systems (BMS), motor controller topologies, and charging stations.',
    logo_url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1558441719-670b357029b7?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'data-analytics-club',
    name: 'Data Analytics Club',
    slug: 'data-analytics-club',
    category: 'Industry 4.0',
    department: 'CSE(DS)',
    department_id: 'dept-cseds',
    faculty_coordinator: 'Mr B Janu Naik',
    description: 'A data-focused club exploring data analysis, visualization, statistical thinking, data-driven decision making, machine learning applications, and practical analytical projects.',
    domains: 'Data Analytics, BI Dashboards, Big Data, Statistical Modeling',
    objectives: 'Equip students with exploratory data analysis techniques, Power BI dashboards, statistical hypothesis testing, and big data handling.',
    logo_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80',
  },

  // ==========================================
  // Category 2: Co-Curricular Activities (11 Clubs)
  // ==========================================
  {
    id: 'energy-management-club',
    name: 'Energy Management Club',
    slug: 'energy-management-club',
    category: 'Co-Curricular Activities',
    department: 'EEE',
    department_id: 'dept-eee',
    faculty_coordinator: 'Mrs. P. Pushpalatha',
    description: 'A club focused on energy awareness, efficient energy usage, renewable energy concepts, conservation practices, and practical approaches to responsible energy management.',
    domains: 'Energy Auditing, Solar/Wind Power, Conservation, Smart Grids',
    objectives: 'Conduct campus energy audits, benchmark departmental electrical loads, and advocate solar energy adoption.',
  },
  {
    id: 'water-management-club',
    name: 'Water Management Club',
    slug: 'water-management-club',
    category: 'Co-Curricular Activities',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Mr L Praveen Kumar',
    description: 'A student club focused on water conservation, efficient water management, sustainable water systems, environmental awareness, and responsible approaches to water resource utilization.',
    domains: 'Water Conservation, Rainwater Harvesting, Hydrology, Watershed Planning',
    objectives: 'Optimize campus rainwater harvesting systems, groundwater recharge monitoring, and water footprint minimization.',
  },
  {
    id: 'waste-management-club',
    name: 'Waste Management Club',
    slug: 'waste-management-club',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mrs S Bhargavi',
    description: 'A sustainability-oriented club promoting responsible waste management, waste reduction, segregation, recycling, environmental awareness, and practical approaches to creating cleaner communities.',
    domains: 'Zero Waste, Recycling, Composting, Environmental Audits',
    objectives: 'Spearhead solid waste segregation drives, organic compost facilities, and plastic-free campus campaigns.',
  },
  {
    id: 'sanitation-hygiene-club',
    name: 'Sanitation and Hygiene Club',
    slug: 'sanitation-hygiene-club',
    category: 'Co-Curricular Activities',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Mr D V D Prasad',
    description: 'A community-oriented club promoting sanitation, hygiene awareness, healthy practices, cleanliness, environmental responsibility, and initiatives that contribute to healthier campus and community environments.',
    domains: 'Public Health, Clean Campus, Water Sanitation, Hygiene Protocols',
    objectives: 'Maintain institutional cleanliness audits, clean drinking water testing, and public hygiene seminars.',
  },
  {
    id: 'rotaract-club',
    name: 'Rotaract Club',
    slug: 'rotaract-club',
    category: 'Co-Curricular Activities',
    department: 'CSE',
    department_id: 'dept-cse',
    faculty_coordinator: 'Mr.Manas Kumar Yogi',
    description: 'A student service-oriented community encouraging leadership, volunteering, social responsibility, community engagement, and collaborative initiatives that create positive social impact.',
    domains: 'Community Leadership, Social Service, Humanitarian Outreach, Youth Action',
    objectives: 'Organize blood donation camps, rural education drives, youth leadership roundtables, and disaster relief aid.',
  },
  {
    id: 'ncc',
    name: 'NCC',
    slug: 'ncc',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Dr.B.Adinarayana',
    description: 'A student organization centered on discipline, leadership, teamwork, physical development, civic responsibility, and structured activities that encourage personal development and service.',
    domains: 'National Service, Leadership, Drill & Fitness, Civic Discipline',
    objectives: 'Instill character, comradeship, secular outlook, spirit of adventure, and ideals of selfless service amongst students.',
  },
  {
    id: 'hope-for-change-club',
    name: 'Hope for a Change Club',
    slug: 'hope-for-change-club',
    category: 'Co-Curricular Activities',
    department: 'ECE',
    department_id: 'dept-ece',
    faculty_coordinator: 'Mr.M.Bramharaju',
    description: 'A student-led community focused on social awareness, volunteering, community engagement, personal development, and initiatives intended to encourage positive change.',
    domains: 'Social Innovation, Student Advocacy, Civic Engagement, Impact Initiatives',
    objectives: 'Foster social consciousness through policy debates, village adoption programs, and educational fundraisers.',
  },
  {
    id: 'sports-and-game-club',
    name: 'Sports and Game Club',
    slug: 'sports-and-game-club',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Dr.B.Adinarayana',
    description: 'A student community promoting sports, physical activity, teamwork, healthy competition, recreation, and participation in athletic and gaming activities.',
    domains: 'Athletics, Team Sports, Fitness & Conditioning, Tournament Operations',
    objectives: 'Coordinate collegiate athletic meets, indoor chess/badminton leagues, cricket/football tournaments, and physical wellness programs.',
  },
  {
    id: 'nss',
    name: 'NSS',
    slug: 'nss',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mr P.Raja Sekhar Phaneendra',
    description: 'A service-oriented student community encouraging volunteering, community participation, social responsibility, civic awareness, and activities that contribute to community development.',
    domains: 'Rural Development, Social Service, Health Camps, Environmental Drives',
    objectives: 'Uphold the motto "Not Me But You" through seven-day special village camps, pulse polio immunization drives, and literacy campaigns.',
  },
  {
    id: 'cultural-club',
    name: 'Cultural Club',
    slug: 'cultural-club',
    category: 'Co-Curricular Activities',
    department: 'CSE(AI)',
    department_id: 'dept-cseai',
    faculty_coordinator: 'Mrs K.L. Viveka',
    description: 'A student community celebrating creativity, cultural expression, performing arts, traditions, music, dance, literature, and collaborative cultural activities.',
    domains: 'Music, Dance, Theatre, Literary Arts, Fest Operations',
    objectives: 'Orchestrate annual cultural fests, performing arts ensembles, traditional heritage celebrations, and creative arts exhibitions.',
  },
  {
    id: 'greenary-club',
    name: 'Greenary Club',
    slug: 'greenary-club',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Dr. N. Prasanthi',
    description: 'An environmental club promoting greenery, plantation activities, ecological awareness, campus sustainability, environmental responsibility, and initiatives supporting a healthier natural environment.',
    domains: 'Campus Afforestation, Botanical Conservation, Eco-Awareness, Biodiversity',
    objectives: 'Coordinate sapling plantation drives, maintain college botanical gardens, and run environmental sustainability awareness seminars.',
  },

  // ==========================================
  // Category 3: Extra-Curricular Activities (13 Clubs)
  // ==========================================
  {
    id: 'press-club',
    name: 'Press Club',
    slug: 'press-club',
    category: 'Extra-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mrs. M. Madhavi',
    description: 'A student media community focused on journalism, campus communication, reporting, interviewing, writing, photography, and responsible storytelling about university activities.',
    domains: 'Campus Journalism, Editorial Design, Media Reporting, Photography',
    objectives: 'Publish the quarterly campus engineering newsletter, document institutional events, and produce student interviews.',
  },
  {
    id: 'toast-masters-club',
    name: 'Toast Masters Club',
    slug: 'toast-masters-club',
    category: 'Extra-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mrs M Madhavi',
    description: 'A communication-focused club helping students develop public speaking, presentation, communication, leadership, confidence, and interpersonal skills through structured practice.',
    domains: 'Public Speaking, Parliamentary Debate, Impromptu Speaking, Leadership',
    objectives: 'Hold weekly Table Topics sessions, speech evaluations, leadership mentoring, and speechcraft masterclasses.',
  },
  {
    id: 'metaverse-club',
    name: 'Metaverse Club',
    slug: 'metaverse-club',
    category: 'Extra-Curricular Activities',
    department: 'CSE(AI)',
    department_id: 'dept-cseai',
    faculty_coordinator: 'Mr. M. Veera Babu',
    description: 'A technology and innovation community exploring immersive digital environments, virtual worlds, 3D experiences, extended reality, digital interaction, and emerging technologies.',
    domains: 'Virtual Worlds, 3D Avatars, Spatial Web, Decentralized Tech',
    objectives: 'Construct immersive virtual campus tours, 3D avatar systems, spatial interaction designs, and virtual reality hackathons.',
  },
  {
    id: 'pragsoft-club',
    name: 'Pragsoft Club',
    slug: 'pragsoft-club',
    category: 'Extra-Curricular Activities',
    department: 'CSE',
    department_id: 'dept-cse',
    faculty_coordinator: 'Mr.S.K.Shankar',
    description: 'A software-focused student community centered on programming, software development, problem solving, technology learning, collaborative projects, and practical engineering skills.',
    domains: 'Software Engineering, Full-Stack Dev, Open Source, Competitive Coding',
    objectives: 'Maintain institutional web and mobile systems, mentor junior students in git/github, and host collegiate algorithmic coding leagues.',
  },
  {
    id: 'iei-mechanical',
    name: 'IEI(I) — Mechanical Engineering',
    slug: 'iei-mechanical',
    category: 'Extra-Curricular Activities',
    department: 'ME',
    department_id: 'dept-me',
    faculty_coordinator: 'Mr A Yeswanth',
    description: 'A professional engineering community associated with mechanical engineering, encouraging technical learning, engineering awareness, professional development, and practical engagement with engineering concepts.',
    domains: 'Mechanical Standards, Thermal Engineering, Manufacturing Innovations, Professional Accreditation',
    objectives: 'Host IEI student conventions, industrial guest lectures, technical paper presentations, and machine design symposiums.',
  },
  {
    id: 'go-kart-club',
    name: 'GO-KART Club',
    slug: 'go-kart-club',
    category: 'Extra-Curricular Activities',
    department: 'ME',
    department_id: 'dept-me',
    faculty_coordinator: 'Mr.M. Sunil Raj',
    description: 'An engineering-focused club centered on go-kart design, vehicle systems, mechanical engineering, fabrication, testing, teamwork, and hands-on automotive engineering projects.',
    domains: 'Motorsport Engineering, Chassis Design, Braking Systems, Vehicle Dynamics',
    objectives: 'Fabricate competition-grade go-karts, run steering geometry FEA simulations, test braking systems, and compete in national karting challenges.',
  },
  {
    id: 'spark-wit-club',
    name: 'Spark WIT Club',
    slug: 'spark-wit-club',
    category: 'Extra-Curricular Activities',
    department: 'IT',
    department_id: 'dept-it',
    faculty_coordinator: 'Mrs A.Manga Devi',
    description: 'A student community encouraging technology learning, innovation, collaboration, professional development, and participation in activities that help students build practical technical and leadership skills.',
    domains: 'Women in Tech, Technical Skill Building, Career Mentorship, Hackathons',
    objectives: 'Empower female engineers with tech leadership bootcamps, coding mentorship, industry executive sessions, and career workshops.',
  },
  {
    id: 'iete',
    name: 'IETE',
    slug: 'iete',
    category: 'Extra-Curricular Activities',
    department: 'ECE',
    department_id: 'dept-ece',
    faculty_coordinator: 'Dr.V.Radhika',
    description: 'An electronics and communication-focused student community supporting technical learning, professional awareness, innovation, electronics projects, communication technologies, and engineering development.',
    domains: 'Telecommunications, Wireless Systems, RF Design, Signal Processing',
    objectives: 'Advance telecommunication engineering knowledge, conduct antenna design workshops, and organize national IETE student symposiums.',
  },
  {
    id: 'maths-club',
    name: 'Maths Club',
    slug: 'maths-club',
    category: 'Extra-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mr. P. Madhubabu',
    description: 'A mathematics-focused community encouraging logical reasoning, problem solving, mathematical thinking, puzzles, analytical skills, and exploration of mathematical concepts.',
    domains: 'Applied Mathematics, Cryptographic Logic, Puzzles & Olympiads, Quantitative Reasoning',
    objectives: 'Cultivate aptitude for national competitive exams (GATE, CAT), host National Mathematics Day celebrations, and run weekly puzzle challenges.',
  },
  {
    id: 'iei-civil',
    name: 'IEI(I) — Civil Engineering',
    slug: 'iei-civil',
    category: 'Extra-Curricular Activities',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Dr. B.Satyanarayana',
    description: 'A professional engineering community associated with civil engineering, supporting technical learning, professional awareness, engineering activities, and practical understanding of civil engineering concepts.',
    domains: 'Infrastructure Planning, Environmental Engineering, Structural Integrity, Technical Conventions',
    objectives: 'Organize survey camps, structural software trainings (ETABS, STAAD.Pro), bridge design competitions, and site visits.',
  },
  {
    id: 'english-club',
    name: 'English Club',
    slug: 'english-club',
    category: 'Extra-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Dr.S.Prasad',
    description: 'A language and communication-focused club supporting English proficiency, communication skills, creative writing, public speaking, reading, discussion, and confident expression.',
    domains: 'Technical Writing, Corporate Communication, Creative Writing, Linguistics',
    objectives: 'Elevate corporate readiness through mock interview drills, group discussions, vocabulary enrichment, and business correspondence workshops.',
  },
  {
    id: 'acce-i',
    name: 'ACCE(I)',
    slug: 'acce-i',
    category: 'Extra-Curricular Activities',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Dr. B.Satyanarayana',
    description: 'A civil engineering-oriented professional and student community encouraging technical development, engineering awareness, knowledge sharing, and engagement with civil engineering practices.',
    domains: 'Consulting Civil Engineering, Structural Design, Concrete Technology, Professional Standards',
    objectives: 'Connect students with consulting civil engineers, explore advanced concrete mix designs, and evaluate structural safety compliance.',
  },
  {
    id: 'iei-eee',
    name: 'IEI(I) — Electrical & Electronics Engineering',
    slug: 'iei-eee',
    category: 'Extra-Curricular Activities',
    department: 'EEE',
    department_id: 'dept-eee',
    faculty_coordinator: 'Mr. S .Nanibabu',
    description: 'A professional engineering community associated with electrical and electronics engineering, supporting technical learning, professional awareness, engineering activities, and practical development.',
    domains: 'High Voltage Engineering, Power Transmission, Electrical Safety, Technical Publications',
    objectives: 'Conduct industrial substation visits, smart metering demos, circuit simulation challenges, and IEI national student paper contests.',
  },
  {
    id: 'ieee-student-branch',
    name: 'IEEE Student Branch',
    slug: 'ieee-student-branch',
    category: 'Extra-Curricular Activities',
    department: 'ECE',
    department_id: 'dept-ece',
    faculty_coordinator: 'Dr. V. Sailaja',
    description: 'The IEEE Student Branch at Pragati Engineering College actively engages engineering scholars in global technological advancements, hosting distinguished expert lectures, signal processing workshops, and IEEE humanitarian technology projects.',
    domains: 'Wireless Communications, IEEE Standards, Signal Processing, Robotics & Automation',
    objectives: 'Organize annual IEEE day symposiums, technical paper presentations, women-in-engineering (WIE) tracks, and global IEEE project competitions.',
  },
  {
    id: 'gdsc-pec',
    name: 'Google Developer Student Club (GDSC)',
    slug: 'gdsc-pec',
    category: 'Industry 4.0',
    department: 'CSE',
    department_id: 'dept-cse',
    faculty_coordinator: 'Dr. M. Radhika Mani',
    description: 'Google Developer Student Club at Pragati Engineering College provides a vibrant platform for students to master Google technologies, Android app development, Google Cloud Platform, TensorFlow, and open-source software building.',
    domains: 'Android Dev, Google Cloud Platform, Flutter, Machine Learning, Web Technologies',
    objectives: 'Host Google Solution Challenge buildathons, Google Cloud Study Jams, Flutter cross-platform bootcamps, and open-source hackathons.',
  },
  {
    id: 'csi-student-chapter',
    name: 'CSI Student Chapter',
    slug: 'csi-student-chapter',
    category: 'Extra-Curricular Activities',
    department: 'CSE',
    department_id: 'dept-cse',
    faculty_coordinator: 'Dr. D.V. Manjula',
    description: 'The Computer Society of India (CSI) Student Chapter in the CSE Department organizes Machine Learning Project Expos, Scratch Programming workshops, national IT quizzes, AI/ML technical seminars, and placement preparation series.',
    domains: 'Computer Science, Machine Learning, IT Quizzes, Software Expos, Scratch Programming',
    objectives: 'Host state-level technical symposiums (STRIDES/EPROZYNE), project expos, competitive coding challenges, and guest lectures.',
  },
  {
    id: 'iste-student-chapter',
    name: 'ISTE Student Chapter',
    slug: 'iste-student-chapter',
    category: 'Extra-Curricular Activities',
    department: 'EEE',
    department_id: 'dept-eee',
    faculty_coordinator: 'Mr. K.V. Durga Prasad',
    description: 'The Indian Society for Technical Education (ISTE) Chapter at Pragati Engineering College promotes quality technical education, student-faculty research initiatives, paper contests, and engineering skill development workshops.',
    domains: 'Technical Education, Research Papers, Skill Enhancement, Innovation',
    objectives: 'Coordinate ISTE annual student conventions, technical paper competitions, expert talks on emerging tech, and hands-on skill workshops.',
  },
  {
    id: 'aws-academy-group',
    name: 'PEC-AWS Academy Student Builder Group',
    slug: 'aws-academy-group',
    category: 'Industry 4.0',
    department: 'IT',
    department_id: 'dept-it',
    faculty_coordinator: 'Dr. M. Uma Devi',
    description: 'The AWS Academy Student Builder Group at Pragati Engineering College offers structured cloud computing training, preparing students for AWS Cloud Practitioner and Solutions Architect professional certifications.',
    domains: 'AWS Cloud Architecture, Cloud Security, Serverless Computing, DevOps Pipelines',
    objectives: 'Conduct AWS Cloud certification bootcamps, serverless microservice labs, cloud security challenges, and cloud project exhibitions.',
  },
  {
    id: 'society-for-data-science',
    name: 'Society for Data Science (SfDS)',
    slug: 'society-for-data-science',
    category: 'Industry 4.0',
    department: 'CSE(DS)',
    department_id: 'dept-cseds',
    faculty_coordinator: 'Mr. M.V. Rajesh',
    description: 'Inaugurated at Pragati Engineering College in November 2023, the Society for Data Science empowers students with statistical modeling, big data analytics, predictive AI, and real-world data product showcases.',
    domains: 'Data Science, Big Data Analytics, Predictive Modeling, Machine Learning',
    objectives: 'Host the annual Data Product Panoply, Kaggle-style data science challenges, Python data analytics bootcamps, and industry analytics series.',
  },
];
