export interface PECDepartmentSeed {
  id: string;
  name: string;
  code: string;
  description: string;
}

export interface PECClubSeed {
  id: string;
  name: string;
  slug: string;
  category: 'Industry 4.0' | 'Co-Curricular Activities' | 'Extra-Curricular Activities';
  department: string;
  department_id: string;
  faculty_coordinator: string;
  description: string;
  domains: string;
  objectives: string;
}

export const PEC_DEPARTMENTS: PECDepartmentSeed[] = [
  {
    id: 'dept-ce',
    name: 'Civil Engineering',
    code: 'CE',
    description: 'Department of Civil Engineering, Sustainable Infrastructure, and Environmental Systems',
  },
  {
    id: 'dept-it',
    name: 'Information Technology',
    code: 'IT',
    description: 'Department of Information Technology, Cloud Computing, and Software Engineering',
  },
  {
    id: 'dept-me',
    name: 'Mechanical Engineering',
    code: 'ME',
    description: 'Department of Mechanical Engineering, Robotics, Thermal Systems, and Additive Manufacturing',
  },
  {
    id: 'dept-cse',
    name: 'Computer Science & Engineering',
    code: 'CSE',
    description: 'Department of Computer Science & Engineering, Distributed Systems, and Computing Platforms',
  },
  {
    id: 'dept-csecs',
    name: 'CSE (Cyber Security)',
    code: 'CSE(CS)',
    description: 'Department of Computer Science & Engineering (Cyber Security and Information Defense)',
  },
  {
    id: 'dept-cseaiml',
    name: 'CSE (AI & ML)',
    code: 'CSE(AIML)',
    description: 'Department of Computer Science & Engineering (Artificial Intelligence and Machine Learning)',
  },
  {
    id: 'dept-cseds',
    name: 'CSE (Data Science)',
    code: 'CSE(DS)',
    description: 'Department of Computer Science & Engineering (Data Science and Big Data Analytics)',
  },
  {
    id: 'dept-cseai',
    name: 'CSE (Artificial Intelligence)',
    code: 'CSE(AI)',
    description: 'Department of Computer Science & Engineering (Artificial Intelligence and Cognition)',
  },
  {
    id: 'dept-ece',
    name: 'Electronics & Communication Engineering',
    code: 'ECE',
    description: 'Department of Electronics & Communication Engineering, VLSI, IoT, and Telecommunications',
  },
  {
    id: 'dept-eee',
    name: 'Electrical & Electronics Engineering',
    code: 'EEE',
    description: 'Department of Electrical & Electronics Engineering, EV Technology, and Power Systems',
  },
  {
    id: 'dept-bsh',
    name: 'Basic Sciences & Humanities',
    code: 'BSH',
    description: 'Department of Basic Sciences and Humanities, Mathematics, English, and Environmental Studies',
  },
];

export const PEC_CLUBS: PECClubSeed[] = [
  // ==========================================
  // Category 1: Industry 4.0 (11 Clubs)
  // ==========================================
  {
    id: 'club-green-building',
    name: 'Green Building Club',
    slug: 'green-building-club',
    category: 'Industry 4.0',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Mr L Praveen Kumar',
    description: 'Promotes sustainable construction, green building concepts, energy-efficient design, environmentally responsible materials, and awareness of sustainable practices in the built environment.',
    domains: 'Sustainable Construction, Green Building, Energy Efficiency, Eco Materials',
    objectives: 'Promote LEED and IGBC green building standards, sustainable architectural workflows, and energy simulation tools among civil engineering scholars.',
  },
  {
    id: 'club-gaming',
    name: 'Gaming Club',
    slug: 'gaming-club',
    category: 'Industry 4.0',
    department: 'IT',
    department_id: 'dept-it',
    faculty_coordinator: 'Mr D. Konda Babu',
    description: 'Provides students with a platform to explore gaming, game technology, competitive gaming, game development concepts, and collaborative gaming activities.',
    domains: 'Game Development, Esports, Game Engines, Interactive Media',
    objectives: 'Fosters real-time rendering skills, game loop physics architecture, Unreal/Unity engines, and tactical collegiate esports competitions.',
  },
  {
    id: 'club-robotics',
    name: 'Robotics Club',
    slug: 'robotics-club',
    category: 'Industry 4.0',
    department: 'ME',
    department_id: 'dept-me',
    faculty_coordinator: 'Mr V. V.N.Sarath',
    description: 'Encourages hands-on learning in robotics, automation, embedded systems, mechanical design, programming, and practical robotic applications.',
    domains: 'Robotics, Automation, Embedded Systems, Mechatronics',
    objectives: 'Design autonomous wheeled platforms, robotic manipulators, ROS2 kinematic pipelines, and industrial automation prototypes.',
  },
  {
    id: 'club-ar-vr',
    name: 'AR/VR Club',
    slug: 'ar-vr-club',
    category: 'Industry 4.0',
    department: 'CSE',
    department_id: 'dept-cse',
    faculty_coordinator: 'Mr.A.Avinash',
    description: 'Explores augmented reality, virtual reality, immersive technologies, 3D experiences, and emerging applications of extended reality.',
    domains: 'Augmented Reality, Virtual Reality, Unity 3D, Spatial Computing',
    objectives: 'Build immersive WebXR scenes, headset spatial applications, marker-based AR tracking, and virtual simulation environments.',
  },
  {
    id: 'club-additive-mfg',
    name: 'Additive Manufacturing Club',
    slug: 'additive-manufacturing-club',
    category: 'Industry 4.0',
    department: 'ME',
    department_id: 'dept-me',
    faculty_coordinator: 'Mr P. Ram Prasad',
    description: 'Promotes practical learning in 3D printing, additive manufacturing, digital fabrication, prototyping, materials, and modern manufacturing technologies.',
    domains: '3D Printing, Rapid Prototyping, CAD/CAM, Digital Fabrication',
    objectives: 'Provide hands-on FDM and SLA 3D printing training, slicer optimization, generative design CAD, and functional mechanical prototyping.',
  },
  {
    id: 'club-cyber-security',
    name: 'Cyber Security Club',
    slug: 'cyber-security-club',
    category: 'Industry 4.0',
    department: 'CSE(CS)',
    department_id: 'dept-csecs',
    faculty_coordinator: 'Mrs. K Sireesha',
    description: 'Promotes cybersecurity awareness and practical learning through ethical security, network security, digital safety, security research, workshops, and hands-on activities.',
    domains: 'Ethical Hacking, Network Security, Cryptography, Threat Defense',
    objectives: 'Organize collegiate capture-the-flag competitions, digital forensic workshops, secure code audits, and cyber hygiene drives.',
  },
  {
    id: 'club-cloud-computing',
    name: 'Cloud Computing Club',
    slug: 'cloud-computing-club',
    category: 'Industry 4.0',
    department: 'IT',
    department_id: 'dept-it',
    faculty_coordinator: 'Mr. K Siva Shankar',
    description: 'Helps students learn cloud computing, distributed systems, cloud platforms, deployment, DevOps concepts, and modern cloud-based application technologies.',
    domains: 'Cloud Architecture, AWS/GCP/Azure, DevOps, Microservices',
    objectives: 'Master containerized deployments, Kubernetes orchestration, serverless microservices, and multi-cloud architectural patterns.',
  },
  {
    id: 'club-aiml-turing',
    name: 'AI&ML Turing Club',
    slug: 'aiml-turing-club',
    category: 'Industry 4.0',
    department: 'CSE(AIML)',
    department_id: 'dept-cseaiml',
    faculty_coordinator: 'Mrs L.Yamuna',
    description: 'Provides a platform for learning and applying artificial intelligence, machine learning, data-driven technologies, model development, and practical AI applications.',
    domains: 'Machine Learning, Deep Learning, Computer Vision, Natural Language Processing',
    objectives: 'Develop deep learning pipelines, transformer model fine-tuning, computer vision classification, and applied generative AI solutions.',
  },
  {
    id: 'club-iot',
    name: 'IoT Club',
    slug: 'iot-club',
    category: 'Industry 4.0',
    department: 'ECE',
    department_id: 'dept-ece',
    faculty_coordinator: 'Dr.Subodh Kumar Panda',
    description: 'Explores Internet of Things technologies through connected devices, sensors, embedded systems, automation, communication protocols, and real-world IoT applications.',
    domains: 'Internet of Things, Embedded C, Sensor Networks, Edge Computing',
    objectives: 'Engineer ESP32 and ARM Cortex sensor nodes, MQTT telemetry pipelines, industrial sensor interfacing, and edge computing gateways.',
  },
  {
    id: 'club-ev',
    name: 'Electric Vehicle Club',
    slug: 'electric-vehicle-club',
    category: 'Industry 4.0',
    department: 'EEE',
    department_id: 'dept-eee',
    faculty_coordinator: 'Mr. P.V.V.Ramana',
    description: 'Promotes learning and innovation in electric mobility, EV technologies, batteries, power systems, vehicle electronics, and sustainable transportation.',
    domains: 'EV Powertrains, Battery Management, Power Electronics, Sustainable Mobility',
    objectives: 'Analyze regenerative braking dynamics, lithium-ion battery management systems (BMS), motor controller topologies, and charging stations.',
  },
  {
    id: 'club-data-analytics',
    name: 'Data Analytics Club',
    slug: 'data-analytics-club',
    category: 'Industry 4.0',
    department: 'CSE(DS)',
    department_id: 'dept-cseds',
    faculty_coordinator: 'Mr B Janu Naik',
    description: 'Develops student skills in data analysis, visualization, statistics, data-driven decision making, and practical applications of analytics.',
    domains: 'Data Analytics, BI Dashboards, Big Data, Statistical Modeling',
    objectives: 'Equip students with exploratory data analysis techniques, Power BI dashboards, statistical hypothesis testing, and big data handling.',
  },

  // ==========================================
  // Category 2: Co-Curricular Activities (11 Clubs)
  // ==========================================
  {
    id: 'club-energy-mgmt',
    name: 'Energy Management Club',
    slug: 'energy-management-club',
    category: 'Co-Curricular Activities',
    department: 'EEE',
    department_id: 'dept-eee',
    faculty_coordinator: 'Mrs. P. Pushpalatha',
    description: 'Promotes awareness and practical understanding of energy conservation, efficient energy usage, renewable energy, and sustainable energy management.',
    domains: 'Energy Auditing, Solar/Wind Power, Conservation, Smart Grids',
    objectives: 'Conduct campus energy audits, benchmark departmental electrical loads, and advocate solar energy adoption.',
  },
  {
    id: 'club-water-mgmt',
    name: 'Water Management Club',
    slug: 'water-management-club',
    category: 'Co-Curricular Activities',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Mr L Praveen Kumar',
    description: 'Encourages awareness and practical initiatives related to water conservation, efficient water usage, rainwater management, and sustainable water practices.',
    domains: 'Water Conservation, Rainwater Harvesting, Hydrology, Watershed Planning',
    objectives: 'Optimize campus rainwater harvesting systems, groundwater recharge monitoring, and water footprint minimization.',
  },
  {
    id: 'club-waste-mgmt',
    name: 'Waste Management Club',
    slug: 'waste-management-club',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mrs S Bhargavi',
    description: 'Promotes responsible waste handling, segregation, recycling, waste reduction, environmental awareness, and sustainable waste-management practices.',
    domains: 'Zero Waste, Recycling, Composting, Environmental Audits',
    objectives: 'Spearhead solid waste segregation drives, organic compost facilities, and plastic-free campus campaigns.',
  },
  {
    id: 'club-sanitation-hygiene',
    name: 'Sanitation and Hygiene Club',
    slug: 'sanitation-and-hygiene-club',
    category: 'Co-Curricular Activities',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Mr D V D Prasad',
    description: 'Promotes awareness and responsible practices related to sanitation, hygiene, clean surroundings, public health, and sustainable sanitation systems.',
    domains: 'Public Health, Clean Campus, Water Sanitation, Hygiene Protocols',
    objectives: 'Maintain institutional cleanliness audits, clean drinking water testing, and public hygiene seminars.',
  },
  {
    id: 'club-rotaract',
    name: 'Rotaract Club',
    slug: 'rotaract-club',
    category: 'Co-Curricular Activities',
    department: 'CSE',
    department_id: 'dept-cse',
    faculty_coordinator: 'Mr.Manas Kumar Yogi',
    description: 'Encourages students to participate in community service, leadership development, social initiatives, volunteering, and activities that create positive community impact.',
    domains: 'Community Leadership, Social Service, Humanitarian Outreach, Youth Action',
    objectives: 'Organize blood donation camps, rural education drives, youth leadership roundtables, and disaster relief aid.',
  },
  {
    id: 'club-ncc',
    name: 'NCC',
    slug: 'ncc',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Dr.B.Adinarayana',
    description: 'Provides students opportunities for discipline, leadership, teamwork, service, physical development, and participation in National Cadet Corps activities.',
    domains: 'National Service, Leadership, Drill & Fitness, Civic Discipline',
    objectives: 'Instill character, comradeship, secular outlook, spirit of adventure, and ideals of selfless service amongst students.',
  },
  {
    id: 'club-hope-for-change',
    name: 'Hope for a Change Club',
    slug: 'hope-for-a-change-club',
    category: 'Co-Curricular Activities',
    department: 'ECE',
    department_id: 'dept-ece',
    faculty_coordinator: 'Mr.M.Bramharaju',
    description: 'Encourages students to engage in socially relevant discussions, awareness activities, debates, volunteering, and initiatives focused on positive social change.',
    domains: 'Social Innovation, Student Advocacy, Civic Engagement, Impact Initiatives',
    objectives: 'Foster social consciousness through policy debates, village adoption programs, and educational fundraisers.',
  },
  {
    id: 'club-sports-and-game',
    name: 'Sports and Game Club',
    slug: 'sports-and-game-club',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Dr.B.Adinarayana',
    description: 'Supports student participation in sports and games while promoting fitness, teamwork, discipline, healthy competition, and overall student well-being.',
    domains: 'Athletics, Team Sports, Fitness & Conditioning, Tournament Operations',
    objectives: 'Coordinate collegiate athletic meets, indoor chess/badminton leagues, cricket/football tournaments, and physical wellness programs.',
  },
  {
    id: 'club-nss',
    name: 'NSS',
    slug: 'nss',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mr P.Raja Sekhar Phaneendra',
    description: 'Provides opportunities for students to participate in community service, social responsibility initiatives, awareness programs, volunteering, and community development activities.',
    domains: 'Rural Development, Social Service, Health Camps, Environmental Drives',
    objectives: 'Uphold the motto "Not Me But You" through seven-day special village camps, pulse polio immunization drives, and literacy campaigns.',
  },
  {
    id: 'club-cultural',
    name: 'Cultural Club',
    slug: 'cultural-club',
    category: 'Co-Curricular Activities',
    department: 'CSE(AI)',
    department_id: 'dept-cseai',
    faculty_coordinator: 'Mrs K.L. Viveka',
    description: 'Provides students a platform to explore and showcase cultural talents through arts, performances, celebrations, creative activities, and cultural events.',
    domains: 'Music, Dance, Theatre, Literary Arts, Fest Operations',
    objectives: 'Orchestrate annual cultural fests, performing arts ensembles, traditional heritage celebrations, and creative arts exhibitions.',
  },
  {
    id: 'club-greenary',
    name: 'Greenary Club',
    slug: 'greenary-club',
    category: 'Co-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Dr. N. Prasanthi',
    description: 'Promotes environmental awareness, greenery, plantation activities, campus sustainability, conservation, and responsible environmental practices.',
    domains: 'Campus Afforestation, Botanical Conservation, Eco-Awareness, Biodiversity',
    objectives: 'Coordinate sapling plantation drives, maintain college botanical gardens, and run environmental sustainability awareness seminars.',
  },

  // ==========================================
  // Category 3: Extra-Curricular Activities (13 Clubs)
  // ==========================================
  {
    id: 'club-press',
    name: 'Press Club',
    slug: 'press-club',
    category: 'Extra-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mrs. M. Madhavi',
    description: 'Provides students opportunities to develop skills in communication, journalism, campus reporting, content creation, documentation, and media-related activities.',
    domains: 'Campus Journalism, Editorial Design, Media Reporting, Photography',
    objectives: 'Publish the quarterly campus engineering newsletter, document institutional events, and produce student interviews.',
  },
  {
    id: 'club-toast-masters',
    name: 'Toast Masters Club',
    slug: 'toast-masters-club',
    category: 'Extra-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mrs. M Madhavi',
    description: 'Helps students develop public speaking, communication, presentation, leadership, confidence, and interpersonal skills through structured speaking activities.',
    domains: 'Public Speaking, Parliamentary Debate, Impromptu Speaking, Leadership',
    objectives: 'Hold weekly Table Topics sessions, speech evaluations, leadership mentoring, and speechcraft masterclasses.',
  },
  {
    id: 'club-metaverse',
    name: 'Metaverse Club',
    slug: 'metaverse-club',
    category: 'Extra-Curricular Activities',
    department: 'CSE(AI)',
    department_id: 'dept-cseai',
    faculty_coordinator: 'Mr. M. Veera Babu',
    description: 'Explores emerging immersive technologies, virtual environments, digital experiences, extended reality, creative technology, and future-facing applications.',
    domains: 'Virtual Worlds, 3D Avatars, Spatial Web, Decentralized Tech',
    objectives: 'Construct immersive virtual campus tours, 3D avatar systems, spatial interaction designs, and virtual reality hackathons.',
  },
  {
    id: 'club-pragsoft',
    name: 'Pragsoft Club',
    slug: 'pragsoft-club',
    category: 'Extra-Curricular Activities',
    department: 'CSE',
    department_id: 'dept-cse',
    faculty_coordinator: 'Mr.S.K.Shankar',
    description: 'Provides students with opportunities to strengthen software development skills through programming, technology activities, projects, technical events, and collaborative learning.',
    domains: 'Software Engineering, Full-Stack Dev, Open Source, Competitive Coding',
    objectives: 'Maintain institutional web and mobile systems, mentor junior students in git/github, and host collegiate algorithmic coding leagues.',
  },
  {
    id: 'iei-me',
    name: 'IEI(I) — Mechanical Engineering',
    slug: 'iei-me',
    category: 'Extra-Curricular Activities',
    department: 'ME',
    department_id: 'dept-me',
    faculty_coordinator: 'Mr A Yeswanth',
    description: 'Supports professional and technical development in mechanical engineering through knowledge sharing, technical activities, professional engagement, and engineering-focused learning.',
    domains: 'Mechanical Standards, Thermal Engineering, Manufacturing Innovations, Professional Accreditation',
    objectives: 'Host IEI student conventions, industrial guest lectures, technical paper presentations, and machine design symposiums.',
  },
  {
    id: 'club-go-kart',
    name: 'GO-KART Club',
    slug: 'go-kart-club',
    category: 'Extra-Curricular Activities',
    department: 'ME',
    department_id: 'dept-me',
    faculty_coordinator: 'Mr.M. Sunil Raj',
    description: 'Promotes practical engineering experience through go-kart design, fabrication, mechanical systems, vehicle dynamics, testing, and motorsport-oriented innovation.',
    domains: 'Motorsport Engineering, Chassis Design, Braking Systems, Vehicle Dynamics',
    objectives: 'Fabricate competition-grade go-karts, run steering geometry FEA simulations, test braking systems, and compete in national karting challenges.',
  },
  {
    id: 'club-spark-wit',
    name: 'Spark WIT Club',
    slug: 'spark-wit-club',
    category: 'Extra-Curricular Activities',
    department: 'IT',
    department_id: 'dept-it',
    faculty_coordinator: 'Mrs A.Manga Devi',
    description: 'Provides students a platform for technical learning, communication, professional development, collaborative activities, and technology-focused initiatives.',
    domains: 'Women in Tech, Technical Skill Building, Career Mentorship, Hackathons',
    objectives: 'Empower female engineers with tech leadership bootcamps, coding mentorship, industry executive sessions, and career workshops.',
  },
  {
    id: 'club-iete',
    name: 'IETE',
    slug: 'iete',
    category: 'Extra-Curricular Activities',
    department: 'ECE',
    department_id: 'dept-ece',
    faculty_coordinator: 'Dr.V.Radhika',
    description: 'Promotes learning and professional development in electronics, telecommunications, communication technologies, engineering practices, and related technical activities.',
    domains: 'Telecommunications, Wireless Systems, RF Design, Signal Processing',
    objectives: 'Advance telecommunication engineering knowledge, conduct antenna design workshops, and organize national IETE student symposiums.',
  },
  {
    id: 'club-maths',
    name: 'Maths Club',
    slug: 'maths-club',
    category: 'Extra-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Mr. P. Madhubabu',
    description: 'Encourages mathematical thinking, problem solving, logical reasoning, mathematical applications, competitions, and activities that strengthen quantitative skills.',
    domains: 'Applied Mathematics, Cryptographic Logic, Puzzles & Olympiads, Quantitative Reasoning',
    objectives: 'Cultivate aptitude for national competitive exams (GATE, CAT), host National Mathematics Day celebrations, and run weekly puzzle challenges.',
  },
  {
    id: 'iei-ce',
    name: 'IEI(I) — Civil Engineering',
    slug: 'iei-ce',
    category: 'Extra-Curricular Activities',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Dr. B.Satyanarayana',
    description: 'Supports professional and technical development in civil engineering through technical learning, professional activities, knowledge sharing, and engineering engagement.',
    domains: 'Infrastructure Planning, Environmental Engineering, Structural Integrity, Technical Conventions',
    objectives: 'Organize survey camps, structural software trainings (ETABS, STAAD.Pro), bridge design competitions, and site visits.',
  },
  {
    id: 'club-english',
    name: 'English Club',
    slug: 'english-club',
    category: 'Extra-Curricular Activities',
    department: 'BSH',
    department_id: 'dept-bsh',
    faculty_coordinator: 'Dr.S.Prasad',
    description: 'Develops students\' English communication, vocabulary, writing, public speaking, presentation, reading, and interpersonal communication skills.',
    domains: 'Technical Writing, Corporate Communication, Creative Writing, Linguistics',
    objectives: 'Elevate corporate readiness through mock interview drills, group discussions, vocabulary enrichment, and business correspondence workshops.',
  },
  {
    id: 'club-acce-i',
    name: 'ACCE(I)',
    slug: 'acce-i',
    category: 'Extra-Curricular Activities',
    department: 'CE',
    department_id: 'dept-ce',
    faculty_coordinator: 'Dr. B.Satyanarayana',
    description: 'Provides students opportunities for professional development, technical learning, engineering activities, knowledge sharing, and engagement with the relevant professional community.',
    domains: 'Consulting Civil Engineering, Structural Design, Concrete Technology, Professional Standards',
    objectives: 'Connect students with consulting civil engineers, explore advanced concrete mix designs, and evaluate structural safety compliance.',
  },
  {
    id: 'iei-eee',
    name: 'IEI(I) — Electrical and Electronics Engineering',
    slug: 'iei-eee',
    category: 'Extra-Curricular Activities',
    department: 'EEE',
    department_id: 'dept-eee',
    faculty_coordinator: 'Mr. S .Nanibabu',
    description: 'Supports professional and technical development in electrical and electronics engineering through technical learning, professional activities, knowledge sharing, and engineering engagement.',
    domains: 'High Voltage Engineering, Power Transmission, Electrical Safety, Technical Publications',
    objectives: 'Conduct industrial substation visits, smart metering demos, circuit simulation challenges, and IEI national student paper contests.',
  },
];
